language: python
python:
- '2.6'
- '2.7'
- '3.6'
- '3.8'
env:
- REPO_VERSION=1.22
- REPO_VERSION=1.27
- REPO_VERSION=2.8
install:
- pip install -r tests/requirements_pip.txt
- pip install coveralls || true
script:
- if python -m coveralls --version; then make V=1 DEBUGTEST=1 COVERAGE=1 REPO_VERSION=$REPO_VERSION
  check; else make V=1 DEBUGTEST=1 COVERAGE=0 REPO_VERSION=$REPO_VERSION check; fi
after_success:
- if python -m coveralls --version; then cd tests/coverage && coveralls --rcfile=coverage.rc;
  fi
deploy:
  provider: releases
  api_key:
    secure: XpQa+YyL52uL83H0/L7rSY169dBm2KtIgcyBNvNypkfVs8hVEmZCVChlVa0atc+n74sS3sJVihCZzMs+5xFkfR4izplFnDksdXBJeeSAPKfbaSVFLxEXnVk6AtsO7QmCZ1Cg0NvYDLSBKugbcWMpxTFmn6IXxHrapbReIa2W+L1Vuc5vHrIQ8uJ25sO0cfip6M+r6UVgF46FCo1OrRz3kUdw29TcKr5OTUhsZffAmfMoRIeYs7pCl5MvOwhRO6kdXupFfaeY47qGWmuMkrf1yVU11UeI5I2VVfkGdzLvwnrZcOPjSpNQhnYhaidMbN6ljEbKsJfSC2eE54ywtDZJ7kpyWECiipmLskvMXZ1W0Udyo21WBTAvxSV/5+wop7GDLVQh4PHcgGjDO1r4MJAc83+kRuoPyz+QmUf1KRLM5hhehpEyRRA6eQ25MAjj60YEp0hKg747eJUpDypj2WOs3hJPkWFGvedwTTEi2pXz9fKvJbm610r76rDc23VgG8XFJgxsj2urVuRs4tGCOSIDijp7IjbQtJ/nUh88Cx7ZzUZPiIq2hyGfUw/+2CXphRcbDlVgCKoOz4XQypVxJC19YdwaHYXoauyZleTQIURCuw8LYtD+oSsui01Z/Er3Zxbt92n8TBrJw0Ip0cAuz736om0CzF0MsuzfKNsND7vXfAo=
  file: repo-mirror
  on:
    repo: guillon/repo-mirror
    tags: true
    python: '3.6'
    condition: $REPO_VERSION = 2.8
