language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
install:
 - pip install -r tests/requirements_pip.txt --use-mirrors
script:
 - make V=1 DEBUGTEST=1 COVERAGE=1 check
after_success:
 - cd tests/coverage && coveralls --rcfile=coverage.rc --verbose

