version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: make all
          name: build
      - run:
          command: make check
          name: test

workflows:
  main:
    jobs:
      - build-and-test
